FROM jboss/base-jdk:11

ADD target/acmeair-mainservice-java-3.3-bootable.jar /opt/jboss.jar

ENV JAEGER_SERVICE_NAME=jaeger-service
ENV JAEGER_AGENT_HOST=jaeger
ENV JAEGER_REPORTER_LOG_SPANS=false
ENV JAEGER_SAMPLER_TYPE=const
ENV JAEGER_SAMPLER_PARAM=1

EXPOSE 9080 
ENTRYPOINT ["java", "-jar", "-Djboss.bind.address.management=0.0.0.0", "-Djboss.bind.address=0.0.0.0","-Djboss.http.port=9080", "/opt/jboss.jar", "-Djava.net.preferIPv4Stack=true"]
